// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh7Cr5-KHUYRNltLcdqVHe7SyaJwxFh-Q',
    appId: '1:200575109601:web:0c78c691c796876f4feaa0',
    messagingSenderId: '200575109601',
    projectId: 'authtutorial-5d193',
    authDomain: 'authtutorial-5d193.firebaseapp.com',
    storageBucket: 'authtutorial-5d193.firebasestorage.app',
    measurementId: 'G-JZ2VDCMS8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2ZTVZmr-sBhrRc1lLIo031Rm1rbP8C4',
    appId: '1:200575109601:android:8495c4fc0da700e34feaa0',
    messagingSenderId: '200575109601',
    projectId: 'authtutorial-5d193',
    storageBucket: 'authtutorial-5d193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdDb5dE19nfvI2yESA26s3oXWRWXrbhBA',
    appId: '1:200575109601:ios:2662c056ffd918f94feaa0',
    messagingSenderId: '200575109601',
    projectId: 'authtutorial-5d193',
    storageBucket: 'authtutorial-5d193.firebasestorage.app',
    iosBundleId: 'com.example.belajarMobile',
  );
}
